apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aegis
  namespace: aegis
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: aegis
  endpoints:
  - port: https
    path: /metrics
    interval: 15s
