apiVersion: v1
kind: Service
metadata:
  name: aegis
  namespace: aegis
  labels:
    app: aegis
spec:
  type: LoadBalancer
  selector:
    app: aegis
  ports:
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
